#!/usr/bin/env bash
#Process and PID file
ender() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;ender" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap ender SIGQUIT

echo "$$" > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
done
