#!/usr/bin/env bash
#Bash (init) script 11-manage_my_process that manages manage_my_process.
PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="./manage_my_process.sh"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process already started"
        exit 1
    fi

    nohup "$PROCESS_SCRIPT" &> /dev/null &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [ -f "$PID_FILE" ]; then
        kill "$(cat "$PID_FILE")"
        rm -f "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

usage() {
    echo "Usage: $0 {start|stop|restart}"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        usage
        ;;
esac
